Repository rajtilakjee/simone, pull requests merged in 2024-04, with the labels that each got.

#2 Add ffmpeg download link
  README.md
Labels: documentation

#4 Modify README.md and dependencies.md
  README.md
  docs/getting-started/dependencies.md
Labels: documentation

#8 Modify README.md and installation.md in docs
  README.md
  docs/getting-started/installation.md
Labels: documentation, enhancement

#9 Modify main.py to introduce Typer
  requirements.txt
  sample.env
  src/main.py
Labels: enhancement

#10 Modify main.py and installation.md
  docs/getting-started/installation.md
  src/main.py
Labels: documentation, enhancement
